-- Run this in Supabase SQL Editor

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password text not null,
  permissions jsonb not null default '[]'::jsonb
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  "buyPrice" numeric(12,2) not null default 0,
  "sellPrice" numeric(12,2) not null default 0,
  quantity integer not null default 0
);

create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  date date not null default current_date,
  party text,
  customer text,
  items jsonb not null default '[]'::jsonb,
  total numeric(12,2) not null default 0
);

create table if not exists public.purchases (
  id bigint generated by default as identity primary key,
  date date not null default current_date,
  party text,
  supplier text,
  items jsonb not null default '[]'::jsonb,
  total numeric(12,2) not null default 0
);

create table if not exists public.returns (
  id bigint generated by default as identity primary key,
  date date not null default current_date,
  type text not null,
  party text,
  items jsonb not null default '[]'::jsonb,
  total numeric(12,2) not null default 0
);

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  date date not null default current_date,
  category text not null,
  amount numeric(12,2) not null default 0,
  description text
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  date date not null default current_date,
  name text not null,
  customer text not null,
  location text,
  "totalCosts" numeric(12,2) not null default 0,
  "contractValue" numeric(12,2) not null default 0,
  profit numeric(12,2) not null default 0
);

alter table public.projects
  add column if not exists status text not null default 'in_progress';

create table if not exists public.contracts (
  id bigint generated by default as identity primary key,
  date date not null default current_date,
  contract_no text,
  title text,
  customer text not null,
  phone text,
  address text,
  items jsonb not null default '[]'::jsonb,
  total numeric(12,2) not null default 0,
  advance_percent numeric(5,2) not null default 50,
  advance_amount numeric(12,2) not null default 0,
  remaining_amount numeric(12,2) not null default 0,
  status text not null default 'in_progress',
  warranty text,
  terms text,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.maintenances (
  id bigint generated by default as identity primary key,
  date date not null default current_date,
  customer text not null,
  location text,
  map_url text,
  type text,
  status text not null default 'pending',
  description text
);

alter table public.maintenances
  add column if not exists map_url text;

create index if not exists idx_sales_date on public.sales(date);
create index if not exists idx_purchases_date on public.purchases(date);
create index if not exists idx_returns_date on public.returns(date);
create index if not exists idx_expenses_date on public.expenses(date);
create index if not exists idx_projects_date on public.projects(date);
create index if not exists idx_contracts_date on public.contracts(date);
create index if not exists idx_contracts_status on public.contracts(status);
create index if not exists idx_maintenances_date on public.maintenances(date);

insert into public.users (username, password, permissions)
values ('admin', '1234', '["all"]'::jsonb)
on conflict (username) do nothing;
